name: algoritmo-spectral
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - sage>=9.5
  - numpy>=1.21
  - scipy>=1.7
  - sympy>=1.9
  - pandas>=1.3
  - matplotlib>=3.5
  - pytest>=6.2
  - jupyter>=1.0
  - ipywidgets>=7.6
  - sphinx>=4.0
  - sphinx-rtd-theme>=1.0
  - flake8
  - pip
  - pip:
    - -r requirements.txt
