name: algoritmo-spectral
channels:
  - conda-forge
  - defaults
dependencies:
  # Pinned versions for reproducibility
  # Last updated: 2025-10-18
  - python=3.10
  - sage=9.8
  - numpy=1.24.3
  - scipy=1.10.1
  - sympy=1.12
  - pandas=2.0.3
  - matplotlib=3.7.2
  - pytest=7.4.0
  - jupyter=1.0.0
  - ipywidgets=8.0.7
  - sphinx=7.0.1
  - sphinx-rtd-theme=1.2.2
  - flake8=6.0.0
  - pip=23.1.2
  - pip:
    - -r requirements.txt
