import AdelicBSD.Constants
import AdelicBSD.Zeta
import AdelicBSD.GoldenRatio
import AdelicBSD.Emergence
import AdelicBSD.Main
import AdelicBSD.BSDFinal
import AdelicBSD.SelmerDesc
import AdelicBSD.Traces.ModularParam
import AdelicBSD.BSDStatement
import AdelicBSD.BirchSwinnertonDyerFinal
