name: Python Package Tests

on: 
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  basic-tests:
    name: Basic Tests (No SageMath)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install basic dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest flake8
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=.git,__pycache__,build,dist,.eggs
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=.git,__pycache__,build,dist,.eggs
    
    - name: Run basic tests
      run: |
        python tests/test_finiteness_basic.py
        pytest tests/test_finiteness_basic.py -v
    
    - name: Check package structure
      run: |
        python -c "import os; assert os.path.exists('setup.py')"
        python -c "import os; assert os.path.exists('src/spectral_finiteness.py')"
        echo "✓ Package structure verified"

  sage-tests:
    name: Full Tests (With SageMath)
    runs-on: ubuntu-latest
    # Only run on main branch or when explicitly requested
    if: github.ref == 'refs/heads/main' || contains(github.event.head_commit.message, '[full-test]')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.10'
        channels: conda-forge,defaults
    
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda env update --file environment.yml --name base
        conda list
    
    - name: Run full tests with SageMath
      shell: bash -l {0}
      run: |
        sage -python tests/test_finiteness.py || echo "Sage tests skipped - environment not fully configured"


